import React,{useState,useEffect} from 'react'
import { View} from 'react-native'
import { TextInput } from 'react-native-paper'
import CocktailAPI from '../CocktailAPI'
import CardList from './CardList'


const drinks = {
  "drinks": [
    {
      "idDrink": "11993",
      "strDrink": "Quentin",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "In a shaker half-filled with ice cubes, combine the rum, Kahlua, and cream. Shake well. Strain into a cocktail glass and garnish with the nutmeg.",
      "strInstructionsES": null,
      "strInstructionsDE": "In einem Shaker, der halb mit Eiswürfeln gefüllt ist, Rum, Kahlua und Sahne mischen. Gut schütteln. In ein Cocktailglas abseihen und mit der Muskatnuss garnieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "In uno shaker riempito a metà con cubetti di ghiaccio, unire il rum, il Kahlua e la panna. Filtrare in una coppetta da cocktail e guarnire con la noce moscata. Agitare bene.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/spxtqp1478963398.jpg",
      "strIngredient1": "Dark rum",
      "strIngredient2": "Kahlua",
      "strIngredient3": "Light cream",
      "strIngredient4": "Nutmeg",
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 1\/2 oz ",
      "strMeasure2": "1\/2 oz ",
      "strMeasure3": "1 oz ",
      "strMeasure4": "1\/8 tsp grated ",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-11-12 15:09:58"
    },
    {
      "idDrink": "17221",
      "strDrink": "Boozy Snickers Milkshake",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Milk \/ Float \/ Shake",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Mason jar",
      "strInstructions": "Place the snickers bars in a plastic bag and roll over them with a rolling pin until crushed. Add crushed snickers pieces, ice cream, milk, caramel sauce, chocolate sauce, and chocolate liquor to a blender. Blend until shake is thick and frothy. Pour into glasses and top with chocolate liquor and whip cream.",
      "strInstructionsES": null,
      "strInstructionsDE": "Legen Sie die Snickers in einen Plastikbeutel und rollen Sie sie mit einem Nudelholz darüber, bis sie zerquetscht sind. Füge zerdrückte Snickers, Eis, Milch, Karamellsauce, Schokoladensauce und Schokoladenlikör in einen Mixer. Mischen, bis der Shake dick und schaumig ist. In Gläser füllen und mit Schokoladenlikör und Schlagsahne auffüllen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Metti le barrette per snickers in un sacchetto di plastica e arrotolale con un mattarello fino a schiacciarle.\r\nAggiungere pezzi di snickers schiacciati, gelato, latte, salsa al caramello, salsa al cioccolato e liquore al cioccolato in un frullatore.\r\nFrullare fino a ottenere un frullato denso e spumoso.\r\nVersare nei bicchieri e guarnire con liquore al cioccolato e panna montata.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/861tzm1504784164.jpg",
      "strIngredient1": "Vanilla Ice-Cream",
      "strIngredient2": "Milk",
      "strIngredient3": "Godiva liqueur",
      "strIngredient4": "Whipped Cream",
      "strIngredient5": "caramel sauce",
      "strIngredient6": "chocolate sauce",
      "strIngredient7": "Mini-snickers bars",
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "3 cups ",
      "strMeasure2": "1 cup ",
      "strMeasure3": "1\/2 cup ",
      "strMeasure4": "for topping",
      "strMeasure5": "4 tablespoons\r\n",
      "strMeasure6": "4 tablespoons\r\n",
      "strMeasure7": "15\r\n",
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-07 12:36:04"
    },
    {
      "idDrink": "11991",
      "strDrink": "Queen Elizabeth",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Stir all ingredients with ice, strain into a cocktail glass, and serve.",
      "strInstructionsES": null,
      "strInstructionsDE": "Alle Zutaten mit Eis verrühren, in ein Cocktailglas abseihen und servieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Mescolare tutti gli ingredienti con ghiaccio, filtrare in una coppetta da cocktail e servire.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/vpqspv1478963339.jpg",
      "strIngredient1": "Dry Vermouth",
      "strIngredient2": "Gin",
      "strIngredient3": "Benedictine",
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1\/2 oz ",
      "strMeasure2": "1 1\/2 oz ",
      "strMeasure3": "1 1\/2 tsp ",
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2016-11-12 15:08:59"
    },
    {
      "idDrink": "178345",
      "strDrink": "Hot Toddy",
      "strDrinkAlternate": null,
      "strTags": "Winter",
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Irish coffee cup",
      "strInstructions": "STEP 1\r\nWhisk the whisky and honey together and split between 2 heatproof glasses. Add half of the cinnamon stick to each, then top up with 200ml boiling water.\r\n\r\nSTEP 2\r\nAdd a splash of lemon juice to each, then taste and add more to your preference. Finish each with a slice of lemon, studded with a clove, and serve immediately.",
      "strInstructionsES": null,
      "strInstructionsDE": null,
      "strInstructionsFR": null,
      "strInstructionsIT": "PASSO 1\r\nSbatti il whisky e il miele insieme e dividi in 2 bicchieri. Aggiungere metà della stecca di cannella a ciascuna, quindi rabboccare con 200 ml di acqua bollente.\r\n\r\nPASSO 2\r\nAggiungi una spruzzata di succo di limone a ciascuno, quindi assaggia e aggiungi altro a tua preferenza. Terminate ciascuna con una fetta di limone, guarnire con uno spicchio, e servite subito.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/ggx0lv1613942306.jpg",
      "strIngredient1": "Whiskey",
      "strIngredient2": "Honey",
      "strIngredient3": "Cinnamon",
      "strIngredient4": "lemon",
      "strIngredient5": "Cloves",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "50 ml",
      "strMeasure2": "15 ml",
      "strMeasure3": "1",
      "strMeasure4": "1",
      "strMeasure5": "2",
      "strMeasure6": "",
      "strMeasure7": "",
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": "https:\/\/www.flickr.com\/photos\/patruby\/7343589018",
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": null
    },
    {
      "idDrink": "13214",
      "strDrink": "Pisco Sour",
      "strDrinkAlternate": null,
      "strTags": "IBA,NewEra",
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": "New Era Drinks",
      "strAlcoholic": "Alcoholic",
      "strGlass": "Cocktail glass",
      "strInstructions": "Vigorously shake and strain contents in a cocktail shaker with ice cubes, then pour into glass and garnish with bitters.\r\n",
      "strInstructionsES": null,
      "strInstructionsDE": "Den Inhalt in einem Cocktailshaker mit Eiswürfeln kräftig schütteln und abseihen, dann in ein Glas gießen und mit Bitter garnieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Shakerare vigorosamente e filtrare il contenuto in uno shaker con cubetti di ghiaccio, quindi versare in un bicchiere e guarnire con bitter.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/tsssur1439907622.jpg",
      "strIngredient1": "Pisco",
      "strIngredient2": "Lemon juice",
      "strIngredient3": "Sugar",
      "strIngredient4": "Ice",
      "strIngredient5": "Egg White",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "2 oz ",
      "strMeasure2": "1 oz ",
      "strMeasure3": "1-2 tblsp ",
      "strMeasure4": "1",
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-08-18 15:20:22"
    },
    {
      "idDrink": "11112",
      "strDrink": "Bloody Maria",
      "strDrinkAlternate": null,
      "strTags": "Breakfast,Brunch,Hangover",
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Old-fashioned glass",
      "strInstructions": "Shake all ingredients (except lemon slice) with cracked ice and strain into an old-fashioned glass over ice cubes. Add the slice of lemon and serve.",
      "strInstructionsES": null,
      "strInstructionsDE": "Alle Zutaten (außer Zitronenscheibe) mit zerkleinertem Eis schütteln und über Eiswürfel in ein old-fashioned Glas seihen. Die Zitronenscheibe dazugeben und servieren.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Shakerare tutti gli ingredienti (eccetto la fetta di limone) con ghiaccio tritato e filtrare in un bicchiere vecchio stile su cubetti di ghiaccio.Aggiungere la fetta di limone e servire.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/yz0j6z1504389461.jpg",
      "strIngredient1": "Tequila",
      "strIngredient2": "Tomato juice",
      "strIngredient3": "Lemon juice",
      "strIngredient4": "Tabasco sauce",
      "strIngredient5": "Celery salt",
      "strIngredient6": "Lemon",
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 oz ",
      "strMeasure2": "2 oz ",
      "strMeasure3": "1 dash ",
      "strMeasure4": "1 dash ",
      "strMeasure5": "1 dash ",
      "strMeasure6": "1 slice ",
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-02 22:57:41"
    },
    {
      "idDrink": "13389",
      "strDrink": "Snake Bite (UK)",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Beer",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Pint glass",
      "strInstructions": "Pour ingredients into a pint glass. Drink. Fall over.",
      "strInstructionsES": null,
      "strInstructionsDE": "Zutaten in ein Glas geben. Trink. Fall um.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Versare gli ingredienti in un bicchiere da pinta.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/xuwpyu1441248734.jpg",
      "strIngredient1": "Lager",
      "strIngredient2": "Cider",
      "strIngredient3": null,
      "strIngredient4": null,
      "strIngredient5": null,
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1\/2 pint ",
      "strMeasure2": "1\/2 pint sweet or dry ",
      "strMeasure3": null,
      "strMeasure4": null,
      "strMeasure5": null,
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2015-09-03 03:52:14"
    },
    {
      "idDrink": "16984",
      "strDrink": "Radioactive Long Island Iced Tea",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Ordinary Drink",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Collins Glass",
      "strInstructions": "Pour all ingredients over ice in a very tall glass. Sip cautiously.",
      "strInstructionsES": null,
      "strInstructionsDE": "Alle Zutaten in einem sehr hohen Glas über Eis gießen. Vorsichtig nippen.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Versare tutti gli ingredienti sul ghiaccio in un bicchiere molto alto.\r\nSorseggia con cautela.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/rdvqmh1503563512.jpg",
      "strIngredient1": "Rum",
      "strIngredient2": "Vodka",
      "strIngredient3": "Tequila",
      "strIngredient4": "Gin",
      "strIngredient5": "Triple sec",
      "strIngredient6": "Chambord raspberry liqueur",
      "strIngredient7": "Midori melon liqueur",
      "strIngredient8": "Malibu rum",
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1 oz ",
      "strMeasure2": "1 oz ",
      "strMeasure3": "1 oz ",
      "strMeasure4": "1 oz ",
      "strMeasure5": "1 oz ",
      "strMeasure6": "1 oz ",
      "strMeasure7": "1 oz ",
      "strMeasure8": "1 oz ",
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-08-24 09:31:52"
    },
    {
      "idDrink": "15639",
      "strDrink": "Texas Sling",
      "strDrinkAlternate": null,
      "strTags": null,
      "strVideo": null,
      "strCategory": "Milk \/ Float \/ Shake",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Wine Glass",
      "strInstructions": "Blend with Ice until smooth. Serve in a tulip glass, top with whip cream.",
      "strInstructionsES": null,
      "strInstructionsDE": "Mit Eis mischen, bis es glatt ist. In einem Tulpenglas servieren, mit Schlagsahne bedecken.",
      "strInstructionsFR": null,
      "strInstructionsIT": "Frullare con ghiaccio fino a che liscio.\r\nServire in un bicchiere a tulipano, guarnire con panna montata.",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/ypl13s1504890158.jpg",
      "strIngredient1": "Kahlua",
      "strIngredient2": "Irish cream",
      "strIngredient3": "Amaretto",
      "strIngredient4": "151 proof rum",
      "strIngredient5": "Cream",
      "strIngredient6": null,
      "strIngredient7": null,
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "1\/2 oz ",
      "strMeasure2": "1\/2 oz ",
      "strMeasure3": "1\/2 oz ",
      "strMeasure4": "1\/2 oz Bacardi ",
      "strMeasure5": "1 oz ",
      "strMeasure6": null,
      "strMeasure7": null,
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": "2017-09-08 18:02:39"
    },
    {
      "idDrink": "178314",
      "strDrink": "Gin Basil Smash",
      "strDrinkAlternate": null,
      "strTags": "Europe,Summer",
      "strVideo": null,
      "strCategory": "Cocktail",
      "strIBA": null,
      "strAlcoholic": "Alcoholic",
      "strGlass": "Highball glass",
      "strInstructions": "Muddle Basil leaves (~ 10) with Suggar Syrup in a shaker. Add Gin an Lemon Juice.\r\nFilter and serve in a tumbler with ice",
      "strInstructionsES": null,
      "strInstructionsDE": null,
      "strInstructionsFR": null,
      "strInstructionsIT": "Pestare le foglie di basilico (~ 10) con lo sciroppo di zucchero in uno shaker. Aggiungi gin e succo di limone. Filtrare e servire in un tumbler con ghiaccio",
      "strInstructionsZH-HANS": null,
      "strInstructionsZH-HANT": null,
      "strDrinkThumb": "https:\/\/www.thecocktaildb.com\/images\/media\/drink\/jqh2141572807327.jpg",
      "strIngredient1": "Gin",
      "strIngredient2": "Lemon Juice",
      "strIngredient3": "Sugar Syrup",
      "strIngredient4": "Basil",
      "strIngredient5": "",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": null,
      "strIngredient9": null,
      "strIngredient10": null,
      "strIngredient11": null,
      "strIngredient12": null,
      "strIngredient13": null,
      "strIngredient14": null,
      "strIngredient15": null,
      "strMeasure1": "6 cl",
      "strMeasure2": "2 cl",
      "strMeasure3": "2 cl",
      "strMeasure4": "Whole",
      "strMeasure5": "",
      "strMeasure6": "",
      "strMeasure7": "",
      "strMeasure8": null,
      "strMeasure9": null,
      "strMeasure10": null,
      "strMeasure11": null,
      "strMeasure12": null,
      "strMeasure13": null,
      "strMeasure14": null,
      "strMeasure15": null,
      "strImageSource": null,
      "strImageAttribution": null,
      "strCreativeCommonsConfirmed": "No",
      "dateModified": null
    }
  ]
}

const SearchInput = ({randomDrink,navigation}) => {
  console.log(navigation)
  const [text,setText] = useState('')
  const [popularDrinks,setPopularDrinks] = useState(drinks)
  const [searchData, setSearchData] = useState('')
  const [searchedDrink,setSearchedDrink] = useState('')

    useEffect(() => {
        async function getSearchedDrink(){
          let popDrinks = await CocktailAPI.getTenRandom();

          setPopularDrinks(popDrinks)
          
        }
        
    
        getSearchedDrink();
      }, [])
    
    const handleSubmit = () => {
        
        // console.log(text)
        setSearchData(text)
        setText('')
    }

    return (
        <View>
            <TextInput
            mode='outlined'
            value={text}
            onChangeText={setText}
            onSubmitEditing={handleSubmit}
            label="Search Drink"
            />

            
        <CardList navigation={navigation} drinks={popularDrinks} />
        </View>
    )
}

export default SearchInput

